language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++
  - sudo apt-get install -y tdsodbc unixodbc unixodbc-dev
  - sudo apt-get install -y freetds-dev freetds-common freetds-bin 
  - sudo apt-get install -y python-dev
  - sudo chmod 777 /etc/odbcinst.ini
  - sudo echo "[FreeTDS]" > /etc/odbcinst.ini
  - sudo echo "Driver = /usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so" >> /etc/odbcinst.ini
env:
  global:
    - secure: "dgEyu4q2lY24KN2W0VLIZlm0fYZq1ybkYoZGZOeLoZXxMmfqysxvnmFLd2X+UDVZmHDEFgCIhsT26OwbQr3b7I5+Hgj6T195UZWuwdSfNK5Vt0ydmQ4KDcWqmklhVuDW0H3oku8pxDGLyKi8tu6zp6jJofQ6ZfgyCjD29teA7LQ="
install:
  - pip install Django==1.6.2
  - pip install https://pyodbc.googlecode.com/files/pyodbc-3.0.7.zip
script: python tests/runtests.py --settings=test_django_pyodbc --noinput -v 2