language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++
  - sudo apt-get install -y tdsodbc unixodbc unixodbc-dev
  - sudo apt-get install -y freetds-dev freetds-common freetds-bin 
  - sudo apt-get install -y python-dev
env:
  global:
    - secure: "dgEyu4q2lY24KN2W0VLIZlm0fYZq1ybkYoZGZOeLoZXxMmfqysxvnmFLd2X+UDVZmHDEFgCIhsT26OwbQr3b7I5+Hgj6T195UZWuwdSfNK5Vt0ydmQ4KDcWqmklhVuDW0H3oku8pxDGLyKi8tu6zp6jJofQ6ZfgyCjD29teA7LQ="
install:
  - pip install requests
# command to run tests, e.g. python setup.py test
script: python test.py

install:
  - pip install Django==1.6.2 pyodbc==3.0.7
script: python tests/runtests.py --settings=test_django_pyodbc -v 2